services:
#  stack-api:
#    image: "stack-api"
#    build: .
#    container_name: stack-api
#    ports:
#      - 16800:8080
#    volumes:
#      - D:/SpringBootCourse/file-server/:/file-server/
#    networks:
#      - java_project
#    depends_on:
#      - stack-db

  stack-db:
    image: postgres:16.3-bullseye
    container_name: stack-db
    ports:
      - 1234:5432
    environment:
      POSTGRES_PASSWORD: java@2024
      POSTGRES_USER: java
      POSTGRES_DB: java_project
    volumes:
      - java_final:/var/lib/postgresql/data
    networks:
      - java_project

volumes:
  java_final:

networks:
  java_project:

