services:
#  stack-api:
#    image: "stack-api"
#    build: .
#    container_name: stack-api
#    ports:
#      - 16800:8080
#    volumes:
#      - D:/SpringBootCourse/file-server/:/file-server/
#    networks:
#      - java_project
#    depends_on:
#      - stack-db

  stack-db:
    image: postgres:16.3-bullseye
    container_name: stack-exchange-db
    ports:
      - 1818:5432
    environment:
      POSTGRES_PASSWORD: java@2024
      POSTGRES_USER: java
      POSTGRES_DB: stack_exchange
    volumes:
      - stack_exchange:/var/lib/postgresql/data
    networks:
      - java_pro

volumes:
  stack_exchange:

networks:
  java_pro:

